syntax on
set number
set relativenumber
set cursorline
set hlsearch
set wrap
set clipboard^=unnamed,unnamedplus
set wildmenu

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'mhinz/vim-startify'
Plug 'connorholyday/vim-snazzy'
call plug#end()
let g:SnazzyTransparent = 1
colorscheme snazzy








